name: Print Software Versions

on:
  push:
    branches:
      - master

jobs:
  #  Check Software Versions at the Data Processing Level (Desktop and Server 1)
  check_processing_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print .NET SDK version (Desktop)
        run: |
          echo ".NET SDK version on Desktop:"
          dotnet --version

      - name: Print SuperInstall Installer version (assuming custom version command)
        run: |
          echo "SuperInstall Installer version:"
          # replace 'superinstall --version' with actual command if different
          superinstall --version

      - name: Print .NET Runtime version (Server 1)
        run: |
          echo ".NET Runtime version on Server 1:"
          dotnet --list-runtimes

  # Check Database Version at the Data Access Level (Server 2)
  check_database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print PostgreSQL version
        run: |
          echo "PostgreSQL version on Server 2:"
          psql --version
