name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  # Check Software Versions at the Data Processing Level (Desktop and Server 1)
  check_processing_software_versions:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print .NET SDK version (Desktop)
        run: |
          echo ".NET SDK version on Desktop:"
          dotnet --version

      - name: Print SuperInstall Installer version
        run: |
          echo "SuperInstall Installer version:"
          # Assuming you have a command to check this version; replace with actual command
          echo "Version of SuperInstall is not determined."

      - name: Print .NET Runtime version (Server 1)
        run: |
          echo ".NET Runtime version on Server 1:"
          dotnet --list-runtimes

  check_database_versions:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          echo "Adding PostgreSQL to PATH"
          setx PATH "%PATH%;C:\Program Files\PostgreSQL\17\bin"

      - name: Print PostgreSQL version
        run: |
          echo "PostgreSQL version on Server 2:"
          psql --version || echo "psql not found."
