name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  # Check Software Versions at the Data Processing Level (Desktop and Server 1)
  check_processing_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SuperInstall (if applicable)
        run: |
          echo "Installing SuperInstall..."
          # Use the appropriate command to install SuperInstall
          # For example, if it's available via apt, use:
          sudo apt-get update
          sudo apt-get install -y superinstall  # Change this line as necessary

      - name: Print .NET SDK version (Desktop)
        run: |
          echo ".NET SDK version on Desktop:"
          dotnet --version

      - name: Print SuperInstall Installer version
        run: |
          echo "SuperInstall Installer version:"
          superinstall --version  # Make sure this command is correct

      - name: Print .NET Runtime version (Server 1)
        run: |
          echo ".NET Runtime version on Server 1:"
          dotnet --list-runtimes

  # Check Database Version at the Data Access Level (Server 2)
  check_database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print PostgreSQL version
        run: |
          echo "PostgreSQL version on Server 2:"
          psql --version
