name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  check_processing_software_versions:
    runs-on: windows-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SuperInstall from GitHub (update with the correct repo)
        run: |
          echo "Installing SuperInstall..."
          git clone https://github.com/NeoNono/Laboratory-work-4.git
          cd C:\blazko_lab4_ownrepo\Laboratory-work-4
          .\install.ps1  # Use PowerShell script or the correct command for installation

      - name: Print .NET SDK version (Desktop)
        run: |
          echo ".NET SDK version on Desktop:"
          dotnet --version

      - name: Print SuperInstall Installer version
        run: |
          echo "SuperInstall Installer version:"
          superinstall --version  

      - name: Print .NET Runtime version (Server 1)
        run: |
          echo ".NET Runtime version on Server 1:"
          dotnet --list-runtimes

  check_database_versions:
    runs-on: windows-latest 

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print PostgreSQL version
        run: |
          echo "PostgreSQL version on Server 2:"
          psql --version
