name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  # Check Software Versions at the Data Processing Level (Desktop and Server 1)
  check_processing_software_versions:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print .NET SDK version (Desktop)
        run: |
          echo ".NET SDK version on Desktop:"
          dotnet --version

      - name: Print SuperInstall Installer version
        run: |
          echo "SuperInstall Installer version:"
          # Assuming you have a command to check this version; replace with actual command
          echo "Version of SuperInstall is not determined."

      - name: Print .NET Runtime version (Server 1)
        run: |
          echo ".NET Runtime version on Server 1:"
          dotnet --list-runtimes

 # Check Database Version at the Data Access Level (Server 2)
  check_database_versions:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SQLite
        run: |
          choco install sqlite

      - name: Print SQLite version
        run: |
          echo "SQLite version on Server 2:"
          sqlite3 --version

      - name: Create a sample database and table
        run: |
          sqlite3 test.db "CREATE TABLE IF NOT EXISTS test_table (id INTEGER PRIMARY KEY, name TEXT);"
          sqlite3 test.db "INSERT INTO test_table (name) VALUES ('Sample Entry');"

      - name: Query the sample database
        run: |
          echo "Querying the sample database:"
          sqlite3 test.db "SELECT * FROM test_table;"
